// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileComparer
{
  static class Vsix
  {
    public const string Id = "edc18cad-2422-45f1-908a-7c2fc5ea928f";
    public const string Name = "FileComparer";
    public const string Description = @"Compare files in Visual Studio 2017";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Akhil Mittal";
    public const string Tags = "Compare Files, File Differ, File Comparer";
  }
}
