// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileComparer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCompareFilesCommandPackageString = "32d7fb6e-0f55-407d-8753-64f5205ba2a6";
        public const string guidCompareFilesCommandPackageCmdSetString = "1753e55d-81b2-418e-b4f7-7add6a5c2634";
        public const string guidImagesString = "36f2c508-f525-4c59-a02a-000ba5b7c4e0";
        public static Guid guidCompareFilesCommandPackage = new Guid(guidCompareFilesCommandPackageString);
        public static Guid guidCompareFilesCommandPackageCmdSet = new Guid(guidCompareFilesCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CompareFilesCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
